# -- Common configurations
#export PY=/home/esetstore/bytescheduler/bin/python
#export PY="/home/esetstore/pytorch1.4/bin/python -W ignore "
export PY="/data/home/sczd744/.conda/envs/py38-hvd/bin/python" # python路径（已修改）
#export PY="/data/home/sczd744/.conda/envs/py310/bin/python" #python路径（已修改）

# export IB_INTERFACE=ib0 # InfiniBand接口
# export IB_INTERFACE=bond0  # 你没有InfiniBand，使用bond0（绑定网卡）
export ETH_INTERFACE=bond0 # 以太网接口（已修改）

unset ETH_INTERFACE
unset IB_INTERFACE

# -- For all-to-all
#export MPIPATH=/home/shaohuais/.local/openmpi-4.0.3
export MPIPATH=/data/apps/openmpi/4.1.5_gcc11.4_ucx1.14.1_cuda11.8 # mpi路径 （已修改）
ETH_MPI_BTC_TCP_IF_INCLUDE=10.244.6.0/23 # IP段

# -- For PS：PS (Parameter Server) 相关（1、3、4可能没用到）
# export LAUNCHBIN=$HOME/bpslaunch # 修改为你的路径
# export CODEHOME=/data/home/sczd744/run/dear_pytorch-master  # 修改为你的代码路径$(pwd)
# export ETH_SCHEDULER_IP=10.244.6.36  # 你的主机IP(参数服务器的)
# export IB_SCHEDULER_IP=10.244.6.36  # 没有IB就用以太网IP
# export NVIDIA_VISIBLE_DEVICES=0,1,2,3  # 根据你的GPU数量调整

# Default worker list: gpu1, gpu2, ...
# Default server list: gpu9, gpu10, ...
# If you want to change the list, please go to change the file: bytes/launch.sh
export WORKER_HOST_PREFIX=gpu

# For debug
# export WFSGD_TIMELINE=timeline.log 
